#pragma once

#define ENC_PID_INT_PERIOD 10

#define SPEED_PID_KP 1
#define SPEED_PID_KI 1
#define SPEED_PID_KD 1

#define MOTOR_OUTPUT_MAX 800

#define OSC_SUPPRESSON_ENABLE 0
#define OSC_SUPR_PERIOD 2000
#define OSC_SUPR_BRAKE_FACTOR 0.6666

#define IR_ON_DELAY_US 1
#define IR_MAX 1000

#define IR_LEFT45_MEAN 1000
#define IR_RIGHT45_MEAN 1000
#define IR_LEFT45_IGNORE -1000
#define IR_RIGHT45_IGNORE -1000

#define IR_LEFT_FWD_MEAN 1000
#define IR_RIGHT_FWD_MEAN 1000
/*
#define IR_LEFT_FWD_IGNORE -1000
#define IR_RIGHT_FWD_IGNORE -1000
*/
#define IR_LEFT_FWD_DETECT_THRESH 1000
#define IR_RIGHT_FWD_DETECT_THRESH 1000
#define IR_FWD_DETECT_THRESH 1000

#define MOBILITY_FWD_DETECT_THRESH 1000
#define MOBILITY_LEFT45_DETECT_THRESH 1000
#define MOBILITY_RIGHT45_DETECT_THRESH 1000

#define ENCODER_TICKS_PER_GRID_CELL 150

#define SEARCHING_SPEED 300
#define FAST_SPEED 800

#define MAX_IR_DIFFERENCE 400
#define SEARCHING_LINEAR_KP .8

#define FAST_LINEAR_KP 0.01
#define FAST_SPEED_CORRECTION_MAX 1200

#define FAST_LINEAR_ACCEL_KP 0.5
#define FAST_LINEAR_DEACCEL_KP 0.5

#define FAST_SPEED_LEFT_BIAS 0
#define FAST_SPEED_RIGHT_BIAS 0

#define FAST_SPEED_IR_CORRECTION 0


#define ROTATE_90_IN_PLACE_ENCODER_INCREMENTS 5000
#define ROTATE_180_IN_PLACE_ENCODER_INCREMENTS 10000
#define ROTATE_COMPENSATION .45
#define ROTATIONAL_KP 1
#define MAX_ROTATIONAL_SPEED 1000
#define MINIMUM_ACCEPTABLE_ANGLE 100

#define FAST_ROTATIONAL_KP 1
//for a given 2 radi the distance travelled in encoder increments
#define FAST_ROTATIONAL_SMALL_TAN_VELOCITY 0
#define FAST_ROTATIONAL_LARGE_TAN_VELOCITY 10000
#define FAST_ROTATIONAL_RADI_RATIO 3
#define FAST_ROTATIONAL_MAX_SPEED 1000
#define FAST_MINIMUM_ACCEPTABLE_ANGLE 100